"""add gateway connectivity layer

Revision ID: 506112579f04
Revises: af5906b5cd24
Create Date: 2026-09-19 17:45:09.853846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '506112579f04'
down_revision: Union[str, Sequence[str], None] = 'af5906b5cd24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gateways', sa.Column('manufacturer', sa.String(), nullable=True))
    op.add_column('gateways', sa.Column('protocol', sa.String(), nullable=False))
    op.add_column('gateways', sa.Column('connection_type', sa.String(), nullable=False))
    op.add_column('gateways', sa.Column('ip_address', sa.String(), nullable=True))
    op.add_column('gateways', sa.Column('port', sa.Integer(), nullable=True))
    op.add_column('gateways', sa.Column('site_id', sa.UUID(), nullable=False))
    op.alter_column('gateways', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('gateways_organization_id_fkey'), 'gateways', type_='foreignkey')
    op.create_foreign_key(None, 'gateways', 'sites', ['site_id'], ['id'])
    op.drop_column('gateways', 'software_version')
    op.drop_column('gateways', 'organization_id')
    op.alter_column('sites', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('sites', 'status')
    op.drop_column('sites', 'created_at')
    op.drop_column('telemetry', 'asset_code')
    op.drop_column('telemetry', 'unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry', sa.Column('unit', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('telemetry', sa.Column('asset_code', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('sites', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('sites', sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('sites', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('gateways', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('gateways', sa.Column('software_version', sa.VARCHAR(), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'gateways', type_='foreignkey')
    op.create_foreign_key(op.f('gateways_organization_id_fkey'), 'gateways', 'organizations', ['organization_id'], ['id'])
    op.alter_column('gateways', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('gateways', 'site_id')
    op.drop_column('gateways', 'port')
    op.drop_column('gateways', 'ip_address')
    op.drop_column('gateways', 'connection_type')
    op.drop_column('gateways', 'protocol')
    op.drop_column('gateways', 'manufacturer')
    # ### end Alembic commands ###
