"""initial MSS architecture

Revision ID: af5906b5cd24
Revises: 
Create Date: 2026-09-19 15:59:40.680980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af5906b5cd24'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.add_column('assets', sa.Column('model', sa.String(), nullable=True))
    op.alter_column('assets', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('assets', 'asset_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('assets', 'manufacturer',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('assets', 'serial_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('assets', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'assets', 'organizations', ['organization_id'], ['id'])
    op.alter_column('organizations', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('organizations', 'industry',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('sites', sa.Column('location', sa.String(), nullable=True))
    op.alter_column('sites', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('sites', 'latitude',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('sites', 'longitude',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    
    op.add_column('telemetry', sa.Column('asset_id', sa.UUID(), nullable=True))
    op.add_column('telemetry', sa.Column('quality', sa.String(), nullable=True))
    op.alter_column('telemetry', 'metric',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('telemetry', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'telemetry', 'assets', ['asset_id'], ['id'])
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry', sa.Column('unit', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('telemetry', sa.Column('asset_code', sa.TEXT(), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'telemetry', type_='foreignkey')
    op.alter_column('telemetry', 'timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('telemetry', 'metric',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_column('telemetry', 'quality')
    op.drop_column('telemetry', 'asset_id')
    op.add_column('sites', sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('sites', 'longitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('sites', 'latitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('sites', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('sites', 'location')
    op.alter_column('organizations', 'industry',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('organizations', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.alter_column('assets', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('assets', 'serial_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('assets', 'manufacturer',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('assets', 'asset_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('assets', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('assets', 'model')
    op.drop_column('assets', 'organization_id')
    # ### end Alembic commands ###
