"""add asset status

Revision ID: f029cf128f6b
Revises: f0a8cfa69232
Create Date: 2026-09-19 19:06:30.659929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f029cf128f6b'
down_revision: Union[str, Sequence[str], None] = 'f0a8cfa69232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'status')
    # ### end Alembic commands ###
